import {
  Tour,
  Destination,
  Trip,
  CommunityPost,
  AIMessage,
  User,
} from '@/types';

// ─── Mock Users ───────────────────────────────────────────────────────────────
export const MOCK_USER: User = {
  id: 'u1',
  name: 'Nguyễn Văn Alex',
  email: 'alex@chektrek.vn',
  phone: '0901234567',
  avatarUrl: 'https://i.pravatar.cc/150?img=8',
  coverUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200',
  bio: 'Trekker đam mê khám phá thiên nhiên Việt Nam 🏔️',
  level: 'Advanced',
  role: 'TREKKER',  // Set to TREKKER to test all screens
  totalDistance: 342.5,
  totalElevation: 12400,
  totalTreks: 47,
  achievements: [
    { id: 'a1', name: 'Summit Seeker', description: 'Leo 5 đỉnh núi', iconName: 'mountain', isUnlocked: true, unlockedAt: '2025-03-15' },
    { id: 'a2', name: 'Forest Walker', description: 'Đi bộ 100km trong rừng', iconName: 'forest', isUnlocked: true, unlockedAt: '2025-05-20' },
    { id: 'a3', name: 'Night Trekker', description: 'Trekking ban đêm', iconName: 'moon', isUnlocked: false },
    { id: 'a4', name: 'Monsoon Master', description: 'Trek trong mùa mưa', iconName: 'rainy', isUnlocked: false },
  ],
  joinedAt: '2024-01-10',
};


// ─── Mock Tours ───────────────────────────────────────────────────────────────
export const MOCK_TOURS: Tour[] = [
  {
    id: 't_cattien',
    title: 'Vườn quốc gia Cát Tiên',
    description: 'Hành trình khám phá Vườn quốc gia Cát Tiên với hệ sinh thái phong phú, đa dạng và cảnh quan thiên nhiên trù phú.',
    destination: 'Tỉnh Đồng Nai, miền Nam Việt Nam',
    province: 'Đồng Nai',
    imageUrls: [
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800'
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600',
    difficulty: 'Easy',
    distance: 25,
    duration: 3, // mapped to 1-3 days in display
    elevation: 150,
    maxParticipants: 15,
    currentParticipants: 6,
    pricePerPerson: 750000,
    currency: 'VND',
    rating: 4.0,
    reviewCount: 92,
    highlights: ['Bàu Sấu', 'Cây Tùng cổ thụ', 'Trekking xuyên rừng'],
    itinerary: [],
    reviews: [],
    guideId: 'g1',
    guideName: 'Nguyễn Đình Tùng',
    tags: ['forest', 'nature'],
    isFeatured: true,
    availableDates: ['2026-06-15'],
    status: 'active',
    createdAt: '2026-05-01',
  },
  {
    id: 't1',
    title: 'Highland Peaks Trail',
    description: 'Hành trình leo núi đỉnh cao với cảnh quan hùng vĩ. Tuyến đường này đưa bạn qua những cánh rừng thông nguyên sinh, vượt những đèo núi hiểm trở và chinh phục đỉnh cao nhất trong khu vực. Phù hợp cho những trekker có kinh nghiệm muốn thử thách bản thân.',
    destination: 'Fansipan, Sapa',
    province: 'Lào Cai',
    imageUrls: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
    difficulty: 'Hard',
    distance: 12.4,
    duration: 8,
    elevation: 3143,
    maxParticipants: 12,
    currentParticipants: 8,
    pricePerPerson: 1500000,
    currency: 'VND',
    rating: 4.9,
    reviewCount: 156,
    highlights: ['Đỉnh Fansipan 3143m', 'Rừng nguyên sinh', 'Sunrise điểm đỉnh'],
    itinerary: [
      { day: 1, title: 'Xuất phát Trạm Tôn', description: 'Khởi hành từ trạm Tôn lúc 5h sáng, leo qua rừng thông đến trại dừng chân đầu tiên.', distance: 5.2, elevation: 800, duration: 4 },
      { day: 1, title: 'Đỉnh Fansipan', description: 'Chinh phục đỉnh Fansipan 3143m. Tận hưởng cảnh biển mây.', distance: 7.2, elevation: 2343, duration: 4 },
    ],
    reviews: [
      { id: 'r1', userId: 'u2', userName: 'Trần Minh', userAvatarUrl: 'https://i.pravatar.cc/150?img=3', rating: 5, comment: 'Trải nghiệm tuyệt vời! Hướng dẫn viên rất tận tình.', createdAt: '2025-05-10' },
      { id: 'r2', userId: 'u3', userName: 'Lê Hương', rating: 4.8, comment: 'Cảnh đẹp mê hồn, nhưng khá mệt. Cần chuẩn bị thể lực tốt.', createdAt: '2025-04-22' },
    ],
    guideId: 'g1',
    guideName: 'Nguyễn Đình Tùng',
    guideAvatarUrl: 'https://i.pravatar.cc/150?img=12',
    tags: ['mountain', 'summit', 'challenging'],
    isFeatured: true,
    availableDates: ['2026-06-15', '2026-06-22', '2026-07-05'],
    status: 'active',
    createdAt: '2025-12-01',
  },
  {
    id: 't2',
    title: 'Emerald Canopy Walk',
    description: 'Tuyến đi bộ qua rừng nhiệt đới với hệ sinh thái phong phú. Cảm nhận thiên nhiên yên bình qua những con đường mòn xanh mát.',
    destination: 'Cúc Phương',
    province: 'Ninh Bình',
    imageUrls: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
      'https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?w=800',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    difficulty: 'Easy',
    distance: 5.2,
    duration: 3,
    elevation: 200,
    maxParticipants: 20,
    currentParticipants: 14,
    pricePerPerson: 450000,
    currency: 'VND',
    rating: 4.7,
    reviewCount: 89,
    highlights: ['Rừng nguyên sinh', 'Thác nước', 'Động vật hoang dã'],
    itinerary: [
      { day: 1, title: 'Cổng vào Cúc Phương', description: 'Bắt đầu từ cổng vào vườn quốc gia.', distance: 5.2, elevation: 200, duration: 3 },
    ],
    reviews: [],
    guideId: 'g2',
    guideName: 'Phạm Thanh Hải',
    tags: ['forest', 'easy', 'nature'],
    isFeatured: true,
    availableDates: ['2026-06-10', '2026-06-17', '2026-06-24'],
    status: 'active',
    createdAt: '2025-11-15',
  },
  {
    id: 't3',
    title: 'Sa Mu U Bò Discovery',
    description: 'Khám phá vùng đất huyền bí Sa Mu U Bò với những cánh đồng hoa rực rỡ và phong cảnh đồng quê tuyệt đẹp.',
    destination: 'Sa Mu U Bò, Nghệ An',
    province: 'Nghệ An',
    imageUrls: [
      'https://images.unsplash.com/photo-1587302002-2dc1f41e89b7?w=800',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1587302002-2dc1f41e89b7?w=600',
    difficulty: 'Moderate',
    distance: 8.6,
    duration: 5,
    elevation: 600,
    maxParticipants: 15,
    currentParticipants: 6,
    pricePerPerson: 850000,
    currency: 'VND',
    rating: 4.8,
    reviewCount: 64,
    highlights: ['Đồng hoa tam giác mạch', 'Bản làng dân tộc', 'Cảnh hoàng hôn'],
    itinerary: [
      { day: 1, title: 'Bản Thống Nhất', description: 'Xuất phát từ bản Thống Nhất.', distance: 4.3, elevation: 300, duration: 2.5 },
      { day: 1, title: 'Sa Mu U Bò', description: 'Đến Sa Mu U Bò lúc hoàng hôn.', distance: 4.3, elevation: 300, duration: 2.5 },
    ],
    reviews: [],
    guideId: 'g3',
    guideName: 'Lô Văn Phương',
    tags: ['meadow', 'ethnic', 'scenic'],
    isFeatured: false,
    availableDates: ['2026-07-01', '2026-07-15'],
    status: 'active',
    createdAt: '2026-01-10',
  },
  {
    id: 't_laothan',
    title: 'Tour leo núi Lảo Thần',
    description: 'Chinh phục nóc nhà Y Tý - đỉnh Lảo Thần cao 2860m với biển mây bồng bềnh kỳ ảo. Đây là điểm trekking săn mây lý tưởng cho người mới bắt đầu.',
    destination: 'Trịnh Tường, Bát Xát, Lào Cai',
    province: 'Lào Cai',
    imageUrls: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800'
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
    difficulty: 'Easy',
    distance: 16,
    duration: 2, // 2 days -> display as 2N1Đ
    elevation: 2860,
    maxParticipants: 10,
    currentParticipants: 4,
    pricePerPerson: 1850000,
    currency: 'VND',
    rating: 4.0,
    reviewCount: 45,
    highlights: ['Chóp đỉnh Lảo Thần 2860m', 'Săn biển mây Y Tý', 'Đón hoàng hôn trên đỉnh'],
    itinerary: [],
    reviews: [],
    guideId: 'g1',
    guideName: 'Nguyễn Đình Tùng',
    tags: ['mountain', 'easy', 'clouds'],
    isFeatured: true,
    availableDates: ['2026-06-12', '2026-06-19'],
    status: 'active',
    createdAt: '2026-05-10',
  },
];

// ─── Mock Destinations ────────────────────────────────────────────────────────
export const MOCK_DESTINATIONS: Destination[] = [
  {
    id: 'd1',
    name: 'Sapa',
    province: 'Lào Cai',
    country: 'Vietnam',
    imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
    description: 'Thiên đường trekking với ruộng bậc thang tuyệt đẹp.',
    trailCount: 24,
    tourCount: 18,
    latitude: 22.3364,
    longitude: 103.8438,
    category: 'mountain',
    isFeatured: true,
  },
  {
    id: 'd2',
    name: 'Cúc Phương',
    province: 'Ninh Bình',
    country: 'Vietnam',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    description: 'Rừng quốc gia với hệ sinh thái phong phú.',
    trailCount: 15,
    tourCount: 12,
    latitude: 20.2543,
    longitude: 105.6589,
    category: 'forest',
    isFeatured: true,
  },
  {
    id: 'd3',
    name: 'Đà Lạt',
    province: 'Lâm Đồng',
    country: 'Vietnam',
    imageUrl: 'https://images.unsplash.com/photo-1562832135-14a35d25edef?w=800',
    description: 'Thành phố ngàn hoa với khí hậu mát mẻ.',
    trailCount: 19,
    tourCount: 22,
    latitude: 11.9404,
    longitude: 108.4583,
    category: 'valley',
    isFeatured: true,
  },
  {
    id: 'd4',
    name: 'Mù Cang Chải',
    province: 'Yên Bái',
    country: 'Vietnam',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    description: 'Ruộng bậc thang kỳ vĩ nhất Việt Nam.',
    trailCount: 11,
    tourCount: 8,
    latitude: 21.8667,
    longitude: 104.0833,
    category: 'mountain',
    isFeatured: false,
  },
];

// ─── Mock Trips ───────────────────────────────────────────────────────────────
export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip1',
    title: 'Fansipan Summer 2026',
    tourId: 't1',
    tourName: 'Highland Peaks Trail',
    startDate: '2026-06-15',
    status: 'planned',
    participants: [
      { userId: 'u1', name: 'Alex', role: 'leader', joinedAt: '2026-05-01', avatarUrl: 'https://i.pravatar.cc/150?img=8' },
      { userId: 'u2', name: 'Minh', role: 'member', joinedAt: '2026-05-05', avatarUrl: 'https://i.pravatar.cc/150?img=3' },
      { userId: 'u3', name: 'Hương', role: 'member', joinedAt: '2026-05-08' },
    ],
    checkpoints: [
      { id: 'cp1', name: 'Trạm Tôn', order: 1, isReached: false, type: 'start', location: { latitude: 22.3, longitude: 103.7 } },
      { id: 'cp2', name: 'Trại Dừng Chân', order: 2, isReached: false, type: 'rest', location: { latitude: 22.32, longitude: 103.75 } },
      { id: 'cp3', name: 'Đỉnh Fansipan', order: 3, isReached: false, type: 'summit', location: { latitude: 22.3031, longitude: 103.7756 } },
    ],
    notes: 'Nhớ mang đủ đồ ấm và thuốc bảo vệ sức khỏe.',
    coverImageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    weatherInfo: {
      temperature: 18,
      humidity: 65,
      windSpeed: 12,
      condition: 'Partly Cloudy',
      icon: 'cloud',
      forecast: [],
    },
    createdAt: '2026-05-01',
  },
  {
    id: 'trip2',
    title: 'Cúc Phương Family Trek',
    startDate: '2026-05-20',
    endDate: '2026-05-20',
    status: 'completed',
    participants: [
      { userId: 'u1', name: 'Alex', role: 'leader', joinedAt: '2026-05-01', avatarUrl: 'https://i.pravatar.cc/150?img=8' },
    ],
    checkpoints: [],
    notes: '',
    totalDistance: 5.2,
    createdAt: '2026-04-15',
  },
];

// ─── Mock Community Posts ──────────────────────────────────────────────────────
export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'p1',
    authorId: 'u2',
    authorName: 'Trần Minh Khoa',
    authorAvatarUrl: 'https://i.pravatar.cc/150?img=15',
    authorLevel: 'Expert',
    content: '🏔️ Vừa chinh phục Fansipan lần thứ 3! Lần này đi vào sáng sớm để bắt sunrise - không thể tả được cảm giác đứng trên đỉnh 3143m nhìn biển mây cuộn trào. Ai muốn đi cùng lần tới không? #Fansipan #Trek #Adventure',
    imageUrls: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    ],
    location: 'Fansipan, Sapa',
    likeCount: 248,
    commentCount: 43,
    shareCount: 12,
    isLiked: false,
    comments: [],
    tags: ['Fansipan', 'Trek', 'Adventure'],
    createdAt: '2026-06-01T07:30:00Z',
  },
  {
    id: 'p2',
    authorId: 'u3',
    authorName: 'Nguyễn Lan Hương',
    authorAvatarUrl: 'https://i.pravatar.cc/150?img=47',
    authorLevel: 'Intermediate',
    content: '🌿 Cúc Phương sau mưa đẹp đến nghẹt thở. Những tán lá long não 1000 năm tuổi tỏa bóng xanh mát. Khuyên mọi người đi vào sáng sớm để tránh nóng nhé! Mình đi tour của Chektrek rất hài lòng 💚',
    imageUrls: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600',
    ],
    location: 'VQG Cúc Phương, Ninh Bình',
    likeCount: 134,
    commentCount: 28,
    shareCount: 8,
    isLiked: true,
    comments: [],
    tags: ['CucPhuong', 'Forest', 'Nature'],
    createdAt: '2026-05-28T14:15:00Z',
  },
];

// ─── Mock AI Messages ─────────────────────────────────────────────────────────
export const MOCK_AI_MESSAGES: AIMessage[] = [
  {
    id: 'msg1',
    role: 'assistant',
    content: 'Xin chào! Tôi là trợ lý AI của Chektrek 🏔️ Tôi có thể giúp bạn lên kế hoạch trekking, tìm tour phù hợp, hoặc giải đáp các câu hỏi về leo núi. Bạn muốn khám phá điểm đến nào?',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    suggestions: [
      'Tour leo Fansipan',
      'Mùa nào đẹp nhất?',
      'Cần chuẩn bị gì?',
    ],
  },
];

